[package]
name = "{{project-name}}-core"
description = "Domain vocabulary for {{project-name}}"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
{% if license != "none" %}license.workspace = true
{% endif %}publish = false

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
