//! Build-time version metadata, generated by `build.rs` via the `built` crate.

// Generated code: undocumented, and most constants are unused.
#[allow(dead_code, missing_docs, clippy::doc_markdown)]
mod built_info {
    include!(concat!(env!("OUT_DIR"), "/built.rs"));
}

/// Returns the short git commit hash, or `"unknown"` when the build knew neither
/// source. `GIT_COMMIT` wins because a container build has no `.git` to read.
pub fn git_commit() -> &'static str {
    option_env!("GIT_COMMIT")
        .filter(|commit| !commit.is_empty())
        .or(built_info::GIT_COMMIT_HASH_SHORT)
        .unwrap_or("unknown")
}

/// Returns the version line for `{{project-name}} version` and startup logs.
pub fn version_string() -> String {
    format!(
        "{} {} (commit {})",
        built_info::PKG_NAME,
        built_info::PKG_VERSION,
        git_commit()
    )
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::version_string;

    #[test]
    fn version_string_contains_package_version() {
        assert!(version_string().contains(env!("CARGO_PKG_VERSION")));
    }
}
